# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outputLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.outputLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.inputData = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.inputData.setObjectName("inputData")
        self.verticalLayout_3.addWidget(self.inputData, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignBottom)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lang1 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.lang1.setObjectName("lang1")
        self.verticalLayout_11.addWidget(self.lang1)
        self.lang2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.lang2.setObjectName("lang2")
        self.verticalLayout_11.addWidget(self.lang2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.action1 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.action1.setObjectName("action1")
        self.verticalLayout_12.addWidget(self.action1)
        self.action2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        self.action2.setObjectName("action2")
        self.verticalLayout_12.addWidget(self.action2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.spinBox = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_4.addWidget(self.spinBox)
        self.translateBtn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.translateBtn.setObjectName("translateBtn")
        self.verticalLayout_4.addWidget(self.translateBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.outputLabel.setText(_translate("Dialog", "Здесь будет результат"))
        self.inputData.setPlaceholderText(_translate("Dialog", "Введите фразу"))
        self.lang1.setText(_translate("Dialog", "Русский язык"))
        self.lang2.setText(_translate("Dialog", "English language"))
        self.action1.setText(_translate("Dialog", "Зашифровать"))
        self.action2.setText(_translate("Dialog", "Расшифровать"))
        self.translateBtn.setText(_translate("Dialog", "Ответ"))
